### ISSUE TITLE
'Namespace' object has no attribute 'hook_url'

### ISSUE THREAD

**Issue by adip99** [fkantelberg/socket-proxy#2]
testing it on Ubuntu 22.04.3 arm

2023-12-06 20:22:13,835 [  INFO  ] CA usage: False
2023-12-06 20:22:13,835 [  INFO  ] Certificate: True
2023-12-06 20:22:13,835 [  INFO  ] Hostname verification: False
2023-12-06 20:22:13,835 [  INFO  ] Minimal TLS Version: TLSv1_2
2023-12-06 20:22:13,835 [  INFO  ] Ciphers: DHE-RSA-AES128-GCM-SHA256, DHE-RSA-AES128-SHA256, DHE-RSA-AES256-GCM-SHA384, DHE-RSA-AES256-SHA256, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-SHA256, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA256, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-CHACHA20-POLY1305, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256
Traceback (most recent call last):
  File "/usr/local/bin/socket_proxy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/socket_proxy/__main__.py", line 457, in main
    run_server()
  File "/usr/local/lib/python3.10/dist-packages/socket_proxy/__main__.py", line 436, in run_server
    server = ProxyServer(
  File "/usr/local/lib/python3.10/dist-packages/socket_proxy/proxy.py", line 54, in __init__
    url=base.config.hook_url,
AttributeError: 'Namespace' object has no attribute 'hook_url'

**Comment by adip99** [comment]
yes installing aiohttp fixed the problem 
funny enough all 3 types of installs ( via pip, via git clone and via zip src) failed to mention that aiohttp is missing 
thank you :)

**Comment by fkantelberg** [comment]
aiohttp is an optional dependency and allows specific functions like the API or the events. Due to this bug it's currently required to be usable.
